### ISSUE TITLE
Link to code on Windows is not resolved in VSCode

### ISSUE THREAD

**Issue by b2m** [explosion/spacy-vscode#27]
Thank you for the implementation of this amazing idea!

On Windows I noticed that the "Go to code" feature in the feature hover does not work.

The error message from VSCode is "Unable to resolve resource ...".

It does however work, when I prepend the registry path with `file:///` or `file://` when the registry path already starts with a slash.

The same problem and solution applies for using VSCode from a Windows machine on a Linux based remote.

**Comment by bdura** [comment]
Hello @b2m, thanks for the catch! We'll take a look at this.
